(Hopefully) Allows Unathi to wear clothes.
genessee-forgot-his-password-again/BlueColonySS13 pull request #2
Opened 2023-02-20 17:18 UTC by MechanicalVulpine

## About The Pull Request

One line-change that adds Unathi to the list of species allowed to wear clothing.

## Why It's Good For The Game

No more forced lizard nudity.

## Changelog
:cl:

fix: Lets Unathi wear clothing, hopefully.

/:cl:

(This is the first ever time I've done anything with Github, so this may not work.)

2023-02-20 18:32 UTC, pitaden commented
Do teshari here have sprites for regular clothes?

2023-02-21 01:28 UTC, Redrover1760 commented
Kind of? I tested this locally with Teshari and it looks like jumpsuits just turn into weird grey jumpsuits, and nothing else seems to work. (also it does work)

However, I did run into a bug playing where, after signing up for a Surgeon (Civilian works fine) I straight up didn't even have an ID/phone. During the test.

2023-02-21 20:46 UTC, Redrover1760 reviewed
Don't forget the Teshari also.

just add SPECIES_TESHARI and it works great.

2023-02-21 20:47 UTC, Redrover1760 requested changes
Don't forget Teshari also. (naked birb causes problems, like not having phones/ID if you are a doctor, for instance)

SPECIES_TESHARI

2023-02-21 23:37 UTC, genessee-forgot-his-password-again commented
Test merged for Thursday. Ping me if you make commits after this so I can have the TM updated.

2023-02-22 01:03 UTC, genessee-forgot-his-password-again commented
@MechanicalVulpine Please expand this PR to include Teshari. I don't really care if their sprites are jank; right now Teshari don't spawn with an ID, and I'd rather have IDed Tesh with weird sprites than IDless Tesh without.

2023-02-22 01:05 UTC, genessee-forgot-his-password-again requested changes
Please include Teshari in this PR.

2023-02-22 01:05 UTC, genessee-forgot-his-password-again commented on code/modules/clothing/clothing.dm
> +	var/list/species_restricted = list(SPECIES_HUMAN, SPECIES_HUMAN_VATBORN, SPECIES_HUMAN_CHILD, SPECIES_HUMAN_TEEN, SPECIES_UNATHI) //Only these species can wear this kit.
```suggestion
	var/list/species_restricted = list(SPECIES_HUMAN, SPECIES_HUMAN_VATBORN, SPECIES_HUMAN_CHILD, SPECIES_HUMAN_TEEN, SPECIES_UNATHI,SPECIES_TESHARI) //Only these species can wear this kit.

```

2023-02-22 03:37 UTC, Redrover1760 requested changes
You forgot a space between SPECIES_UNATHI and SPECIES_TESHARI

2023-02-23 13:11 UTC, pitaden commented
Might be best to do `species_restricted = null` so it doesn't check for species at all, so you don't need to change the list each time a race gets added/removed

2023-02-23 15:01 UTC, merged